// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCEvC_bCXBpMDNnriD632fmq4fImNB8yk',
    appId: '1:480746417470:web:2846f7f13540436c5b906f',
    messagingSenderId: '480746417470',
    projectId: 'gradproj-f7cc0',
    authDomain: 'gradproj-f7cc0.firebaseapp.com',
    storageBucket: 'gradproj-f7cc0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcVHYwntQo7KEelbcLSYNGOilhS3nrLwo',
    appId: '1:480746417470:android:2f7ccadafa04b24e5b906f',
    messagingSenderId: '480746417470',
    projectId: 'gradproj-f7cc0',
    storageBucket: 'gradproj-f7cc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDznexi9RGg4RKnc1gWyx9Tu_RlityGFlI',
    appId: '1:480746417470:ios:fac01275367683125b906f',
    messagingSenderId: '480746417470',
    projectId: 'gradproj-f7cc0',
    storageBucket: 'gradproj-f7cc0.appspot.com',
    iosClientId: '480746417470-ng9e6joqco1648ch6om5s7p011e65pkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDznexi9RGg4RKnc1gWyx9Tu_RlityGFlI',
    appId: '1:480746417470:ios:9f5ecbaee3dc0c355b906f',
    messagingSenderId: '480746417470',
    projectId: 'gradproj-f7cc0',
    storageBucket: 'gradproj-f7cc0.appspot.com',
    iosClientId: '480746417470-nscvdjtg9qao5h73te6up86iqnvumkhr.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradProj.RunnerTests',
  );
}
